### PR TITLE
RELOPS-425 - Update current running inventory

### PR DESCRIPTION
**Pull request by MasterWayZ**
Technically `modules/roles_profiles/manifests/profiles/gecko_3_t_osx_1014_generic_worker.pp` isn't part of the ticket but it's something we have to land anyway..
This comments out the known bad Macs and syncs the staging and prod definitions.

### CODE REVIEW

**Comment by aerickson** [comment]
Add 246 in somewhere?

**Comment by MasterWayZ** [comment]
@aerickson done. added to staging so I can check the machine before adding it to one of the other pools.

**Comment by aerickson** [comment]
Why comment out the offline hosts? Just so we can get through a run on the entire fleet? 

I just worry we forget about the offline hosts and never bring them back, but works for now.

**Review by aerickson — APPROVED** [review]

**Comment by MasterWayZ** [comment]
I am working on a sheet as I will be auditing all machines, so do not worry. I have a plan :)

**Pull request merged**
