### PR TITLE
Remove bhearsum and mtabara from mac signers

### PR DESCRIPTION
**Pull request by escapewindow**
We may add more releng in the future.

### CODE REVIEW

**Comment by gbrownmozilla** [comment]
I don't have a specific need, but am tentatively signed up for cross-training in H1, so please add me.

**Comment by hneiva** [comment]
@escapewindow please add @jcristau :
```
jcristau:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD1coEjA0xXcjmJ7H2kJGWGCW4JkK8JMfzogw94t2VZVFEHFx1YSVE00dObjci8387V0QySsrndt8qIFIbUa4vss1+EtfOnd7kbPCXD8EoWJGv9G70OfdV1uMmDF10heZPdj3OmkWfusvGOEYaOQuuz3HQUYT3YO9F+8llFsCIsyeLj7xcAY8pGvYqj0Fh2uJAc72zetqGjvB7PKJmoYphVHLtEnW1OrvDouhk9fJL1SF06Kf0RmkI7N+bBPVcHYczwkLHY13OA0D8szHentG2557lwN/02UzlY25RNjCEBjlC4IIrVRKdgP4aBl/CijIiJ1tN40qp/edAQ0vjYnAN jcristau@mozilla.com
```

**Comment by escapewindow** [comment]
Added gbrown at his request, though we'll also need to update Relops Duo and this repo's perms.

**Review by davehouse — APPROVED** [review]

**Comment by escapewindow** [comment]
Thanks!

**Comment by aerickson** [comment]
gbrownmozilla has been added to https://github.com/orgs/mozilla-platform-ops/teams/releng/members (which has write on this repo).

Aki, regarding Duo, we just need to invite gbrown?

**Comment by escapewindow** [comment]
> gbrownmozilla has been added to https://github.com/orgs/mozilla-platform-ops/teams/releng/members (which has write on this repo).

Thank you!
Could you also invite @ahal and @hneiva ?

> Aki, regarding Duo, we just need to invite gbrown?

I think so. Do you know how to do that?

**Comment by aerickson** [comment]
Yeah, I've recently gotten access to the Relops Duo.

hneivia and ahal are already present in the account.

dhouse, do you know the process for adding users? There's talk of
self-enrollment, but not sure if we have that enabled. I think releng users
also need to be added to the releng and/or notarization groups, right?

**Comment by davehouse** [comment]
👍 discussed in chat; self-enrollment is off for releng duo and it is manually managed (for security decided in the past)

**Comment by escapewindow** [comment]
> Yeah, I've recently gotten access to the Relops Duo. hneivia and ahal are already present in the account.

Have they been invited to https://github.com/orgs/mozilla-platform-ops/teams/releng/members ? Looks like I'm the only one there that's accepted so far.

**Comment by davehouse** [comment]
@escapewindow ➕  added, and I made you a maintainer for the releng team in that org. So then you can invite or remove as needed

**Pull request merged**
