### PR TITLE
Add mac_single_file behaviour to mac signing workers

### PR DESCRIPTION
**Pull request by bhearsum**
Just need to fill in the scriptworker-scripts rev when that gets merged.

### CODE REVIEW

**Comment by bhearsum** [comment]
This is in support of https://bugzilla.mozilla.org/show_bug.cgi?id=1681836, which we're told is pretty high priority - we're trying to get an iscript deployment done today. The only notable part here is the bug fix to `clean_appstate.pp`, to avoid that prefs file ending up root owned (which will make puppet try to recreate the users again -- which obviously won't work).

**Comment by bhearsum** [comment]
I'm pretty sure that pre_commit failure is not my fault...I'm not touching any shell code here.

**Comment by bhearsum** [comment]
Looks like pre commit is broken on master too, eg: https://app.circleci.com/pipelines/github/mozilla-platform-ops/ronin_puppet/113/workflows/a5758f30-a5bf-4b38-a3ce-107fbf8c0038/jobs/286

**Comment by aerickson** [comment]
> Looks like pre commit is broken on master too, eg: https://app.circleci.com/pipelines/github/mozilla-platform-ops/ronin_puppet/113/workflows/a5758f30-a5bf-4b38-a3ce-107fbf8c0038/jobs/286

Not sure what's going on here. I didn't change any pre-commit stuff in my commit that broke master. Trying to find a fix.

**Review by escapewindow — APPROVED** [review]

**Comment by escapewindow** [comment]
@davehouse @dividehex Any chance we can expedite reviewing+landing this PR?

**Review by davehouse — APPROVED** [review]

**Pull request merged**
