### PR TITLE
Duo auth implemented on mac signing/notarizing hosts

### PR DESCRIPTION
**Pull request by dividehex**
This implements duo_uinix auth on the mac-v3-signing hosts to allow access directly from the vpn and the ssh jumphosts.  I've tested this on mac-v3-signing7.  It also works on Catalina.

While looking at the fw::network file, it clearly needs some clean up.  I'll follow that up in a different PR.

### CODE REVIEW

**Review by bhearsum — APPROVED** [review]
More or less a rubberstamp. Does this mean that my yubikey will no longer work to access these hosts? (Or will it work in addition to Duo?)

**Comment by gcoxmoz** [comment]
Non-blocking comment:  Duo used to have a [puppet module for duo_unix](https://github.com/duosecurity/puppet-duo_unix), but they've abandoned it.  [We resurrected it](https://github.com/mozilla-it/puppet-duo_unix) because we needed it, caught it up to modern, and I'm the de facto maintainer.  If you want to pivot to use it, I'm open to PRs, if you've got use cases that the module should cover.

**Comment by dividehex** [comment]
> 
> 
> More or less a rubberstamp. Does this mean that my yubikey will no longer work to access these hosts? (Or will it work in addition to Duo?)

No. You're yubikey will continue to work when accessing these hosts.  You will need to change you ssh config to remove the ProxyJump configuration. Same duo account and your same yubikey.

**Review by davehouse — APPROVED** [review]

**Comment by dividehex** [comment]
We will need to either re-image all the signers with deploystudio or manual update the vault.yaml on each host before landing this.  I'm also going to wait for @escapewindow to return and review before landing this.

**Review by escapewindow — APPROVED** [review]
> We will need to either re-image all the signers with deploystudio or manual update the vault.yaml on each host before landing this. I'm also going to wait for @escapewindow to return and review before landing this.

Largely a rubber stamp.

I'm mainly concerned with logistics.
If we roll out to the production-mac-signing branch, a) we'll roll out everywhere and will be up a creek if the signing boxes are bricked, and b) we need to make sure we update vault.yaml everywhere before that happens.

If we image, say, one or half of the pool to make sure everything's hunky dory, that'll be safer, but we'll repuppet against an older revision on the production-mac-puppet branch and potentially undo the changes until we're ready to roll out to the entire pool.

Which sounds safer?

Also, when we puppetize the entire pool (and it sticks), that should finally unblock rolling out [the new docker-worker ami](https://bugzilla.mozilla.org/show_bug.cgi?id=1705196).

**Comment by escapewindow** [comment]
From Slack:

1. bring production-mac-signing up to date with master (it is behind master a bit)
2. merge the duo PR into master
3. bless (re-image) one signing host. This will puppetize it against master and apply duo.  (I've tested the deployment on mac-v3-signing7 and it works.)
4. after puppetizing, finish the manual process.  This will switch the branch to production-mac-signing.  Although duo has not been merge to this branch the config will remain in place and duo will continue to work.
5. repeat step 3 and 4 until all signing hosts have duo and are back in prod
6. Finally, merge master (with duo) into production-mac-signing

(1) is done.

**Comment by escapewindow** [comment]
(2) is done (this PR is merged). mac-v3-signing3 is reimaged and back in the pool. I'll leave that overnight, and assuming it looks good, I'll reimage the rest of the pool tomorrow and merge master to production-mac-signing.

**Pull request merged**
