### PR TITLE
[RELENG-364] iscript -11 -15 error code handling

### PR DESCRIPTION
**Pull request by escapewindow**
Should help avoid bustage when puppetizing mac signers mid-task.

### CODE REVIEW

**Comment by escapewindow** [comment]
@bhearsum @davehouse

**Review by bhearsum — DISMISSED** [review]

**Comment by escapewindow** [comment]
Bumped scriptworker to 15f47ca82a0dc0dbe2a27ab1d844ab48824f5c68 for pine level 3.

**Review by davehouse — APPROVED** [review]

**Comment by davehouse** [comment]
@escapewindow is this ready for me to merge it?

**Comment by escapewindow** [comment]
@davehouse yes please! We'll probably puppetize the macs next week.

**Pull request merged**
