### PR TITLE
linux: update git to 2.42

### PR DESCRIPTION
**Pull request by aerickson**
See https://mozilla-hub.atlassian.net/browse/RELOPS-331.

- adds new `linux_package_from_s3_multi.pp` class
- upgrades git to 2.42
- adds a spec test for the specific git version

Also:
- gem updates
- notes on documenting puppet modules

### CODE REVIEW

**Comment by aerickson** [comment]
We're happy with where this is. We've deployed it to a single moonshot host (in a pool suffixed with '-staging').

**Review by rcurranmoz — DISMISSED** [review]

**Comment by aerickson** [comment]
Tests against the staging host/pool look good.

`./mach try fuzzy --full --query "'test-linux1804-64-shippable-qr 'opt-browsertime 'essential" --worker-suffix t-linux-talos-1804=-staging`
- https://treeherder.mozilla.org/jobs?repo=try&revision=58f2cc32f1d4bd21a55df56cf7053d431336b91a

**Review by rcurranmoz — APPROVED** [review]
lgtm

**Comment by aerickson** [comment]
Temporary staging code reverted. We will land and rollout on Monday.

**Pull request merged**
