### PR TITLE
add jmoss, remove grenade

### PR DESCRIPTION
**Pull request by jwmoss**
Adding myself as new engineer on relops team

### CODE REVIEW

**Comment by aerickson** [comment]
It looks like one of the spec tests is failing due to the the group entry being different.

```
  File /etc/group
     ×  content is expected to match /admin:x:[\d]+:jwatkins,dhouse,mcornmesser,aerickson,rthijssen/

```

If you rebase, the bitbar failure should go away.

**Comment by aerickson** [comment]
The linux test can be fixed by changing https://github.com/mozilla-platform-ops/ronin_puppet/blob/ef1430da737cc0fa33374998e0ce2730ee3eff6c/test/integration/linux/inspec/users_spec.rb#L18

**Review by aerickson — CHANGES_REQUESTED** [review]
Please fix the test (see my previous comment).

**Comment by aerickson** [comment]
Hm, the test is still broken for some reason.

**Comment by jwmoss** [comment]
> Hm, the test is still broken for some reason.

Let me re-run the tests to see if they import the updated users_spec.rb

**Review by aerickson — APPROVED** [review]
lgtm. please squash when landing.

**Pull request merged**
