### PR TITLE
Update robustcheckout mercurial extension and remove bundleclone

### PR DESCRIPTION
**Pull request by jcristau**
It seems unfortunate that there's 3 copies of robustcheckout.py (plus at least one more in the cloud_windows branch, as far as I can tell), hopefully that can be consolidated.

My main reason for updating robustcheckout is to pick up the fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1481291

### CODE REVIEW

**Comment by jwmoss** [comment]
I can work on adding these to the windows 10/11 testers.

**Comment by aerickson** [comment]
Looks good from a linux perspective (relying on the automated tests). 

I think we're set regarding windows (cc @jwmoss).

@rcurranmoz and @MasterWayZ thoughts from a Mac perspective? Please approve if it looks good.

**Comment by aerickson** [comment]
Rebased to get the full test suite to run.

**Comment by aerickson** [comment]
Tracking the deployment of this in https://mozilla-hub.atlassian.net/browse/RELOPS-732.

**Comment by MasterWayZ** [comment]
I think it looks good

**Review by aerickson — APPROVED** [review]
lgtm

**Comment by aerickson** [comment]
Will merge this next week (as it will go out immediately on linux hw).

**Comment by jcristau** [comment]
Thanks all!

**Pull request merged**
