### PR TITLE
18.04: add papertrail logging

### PR DESCRIPTION
**Pull request by aerickson**
Adds logging to papertrail.

- papertrail.port and papertrail.host are hiera secrets that need to be set and sent out to all hosts
  - lookups have defaults, so nothing will explode if unset

#### links

https://documentation.solarwinds.com/en/Success_Center/papertrail/Content/kb/configuration/configuring-centralized-logging-from-systemd.htm#

### CODE REVIEW

**Comment by aerickson** [comment]
Testing on t-linux64-ms-001.

**Comment by aerickson** [comment]
Logs viewable at https://my.papertrailapp.com/groups/24579611/events. Filtering appears to be working.

**Comment by aerickson** [comment]
```Warning: Calling function empty() with Numeric value is deprecated.
   (file: /etc/puppet/environments/aerickson/code/modules/linux_papertrail/manifests/init.pp, line: 16)```

**Review by davehouse — APPROVED** [review]
r+

**Pull request merged**
