### PR TITLE
(wip) [RELENG-378] Periodic mac signer puppet

### PR DESCRIPTION
**Pull request by escapewindow**

### CODE REVIEW

**Comment by escapewindow** [comment]
- I think I need another launchd plist for the "cron" task.
- Getting

    ```
Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/Library/LaunchDaemons/com.puppetlabs.puppet.plist] is already declared at (file: /var/root/ronin_puppet/modules/puppet/manifests/disable_atboot.pp, line: 9); cannot redeclare (file: /var/root/ronin_puppet/modules/puppet/manifests/setup.pp, line: 12) (file: /var/root/ronin_puppet/modules/puppet/manifests/setup.pp, line: 12, column: 13) on node mac-v3-signing14.srv.releng.mdc1.mozilla.com
    ```

    which makes me think I should combine the actions in `puppet::disable_atboot` into `puppet::periodic` so I don't have to call both.

**Comment by dividehex** [comment]
> 
> 
>     * I think I need another launchd plist for the "cron" task.
> 
>     * Getting
> 
> 
> > Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: File[/Library/LaunchDaemons/com.puppetlabs.puppet.plist] is already declared at (file: /var/root/ronin_puppet/modules/puppet/manifests/disable_atboot.pp, line: 9); cannot redeclare (file: /var/root/ronin_puppet/modules/puppet/manifests/setup.pp, line: 12) (file: /var/root/ronin_puppet/modules/puppet/manifests/setup.pp, line: 12, column: 13) on node mac-v3-signing14.srv.releng.mdc1.mozilla.com
> 
> which makes me think I should combine the actions in `puppet::disable_atboot` into `puppet::periodic` so I don't have to call both.

I see 3 states a host could be set to regarding puppet execution; atboot, periodic, and disabled.  All three should be mutually exclusive so you can overlap resources and not worry about conflicting resources.

**Comment by escapewindow** [comment]
> I see 3 states a host could be set to regarding puppet execution; atboot, periodic, and disabled. All three should be mutually exclusive so you can overlap resources and not worry about conflicting resources.

I think the problem here was I was calling both `periodic` and `disabled`. Fixed as of https://github.com/mozilla-platform-ops/ronin_puppet/pull/277/commits/08582e54a328dec65c563f140861e002d1f4b47f

**Comment by escapewindow** [comment]
I think this is ready for review. I might create a new PR with rebased commits for clarity.

**Pull request closed without merging**
