### PR TITLE
[bug 1619377] - super rough sketch of notarization poller, for feedback

### PR DESCRIPTION
**Pull request by escapewindow**
@srfraser , @davehouse , I'm looking to add a notarization-poller worker per prod/tb-prod mac:

- this should run on prod/tb-prod, not dep
- we can install notarization-poller in the same venv as iscript
- we need a separate user/pass to run notarization-poller
- we need the notarization user/pass secrets from the `script_config.yaml`, but we'll also add a unique clientId/accessToken for the worker
- we'll need a different config file (`poller.yaml`) and a separate launchd entry / wrapper
- I'm thinking about running these in a `poller/` subdirectory

I see a few ways to do this:

- put a complex `if` block into `signing_worker/init.pp`, to conditionally set up the poller, or
- create a new .pp file that we conditionally call from `signing_worker/init.pp`; this new `.pp` file contains all poller logic
- something else? New module, and the prod/tb-prod machines also use this module?

Do you recommend a particular direction here at the outset?

### CODE REVIEW

**Comment by escapewindow** [comment]
Sharing the venv is probably easier if we either install notarization-poller everywhere, or do it in `init.pp`. We can certainly create a separate venv for notarization-poller if people prefer.

**Comment by davehouse** [comment]
>     * we need a separate user/pass to run notarization-poller

Why does it need to run under a different user? Does the poller need to be separate from some secrets in scriptworker user accounts?

> I see a few ways to do this:
> 
>     * put a complex `if` block into `signing_worker/init.pp`, to conditionally set up the poller, or
> 
>     * create a new .pp file that we conditionally call from `signing_worker/init.pp`; this new `.pp` file contains all poller logic
> 
>     * something else? New module, and the prod/tb-prod machines also use this module?
> 
> 
> Do you recommend a particular direction here at the outset?

With the poller running on the same machine as the signing_worker, putting the poller setup in the signing_worker init sounds logical. I think it would separate it too much to make a new module unless it gets long or too complex in the signing_worker.

Let me know if I can help. Based on the bugs and PR's, the plan looks excellent.

**Comment by escapewindow** [comment]
> > ```
> > * we need a separate user/pass to run notarization-poller
> > ```
> 
> Why does it need to run under a different user? Does the poller need to be separate from some secrets in scriptworker user accounts?

I believe Xcode has a user-level lockfile. We want the poller and notarization workers to be able to work in parallel.

> With the poller running on the same machine as the signing_worker, putting the poller setup in the signing_worker init sounds logical. I think it would separate it too much to make a new module unless it gets long or too complex in the signing_worker.
> 
> Let me know if I can help. Based on the bugs and PR's, the plan looks excellent.

Sweet, I'll give it a shot. Thanks!

**Comment by davehouse** [comment]
> I believe Xcode has a user-level lockfile. We want the poller and notarization workers to be able to work in parallel.

👍 thx. keeping them separated sounds good to avoid potential locks or conflicts. And I'm guessing it will be easier to monitor and debug.

**Comment by escapewindow** [comment]
TODO: set workerGroup to `mdc{1,2}`

**Comment by escapewindow** [comment]
Trying to test this on mac-v3-signing3. My test branch is https://github.com/escapewindow/ronin_puppet/commits/akitest, trying to fix the various errors that come up when puppetizing. (That branch is based off the branch in this PR.)

The latest that I'm not sure how to get around is

```
Error: Could not prefetch user provider 'directoryservice': undefined method `each' for nil:NilClass
Error: Failed to apply catalog: undefined method `each' for nil:NilClass
```

@davehouse if you have any insight, that would help a lot. Thanks!

**Comment by davehouse** [comment]
here's what it shows for me:
```
[dhouse@mac-v3-signing3.srv.releng.mdc1.mozilla.com code]$ sudo su - asasaki
[asasaki@mac-v3-signing3.srv.releng.mdc1.mozilla.com ~]$ cd /etc/puppet/environments/aki/code
[asasaki@mac-v3-signing3.srv.releng.mdc1.mozilla.com code]$ /opt/puppetlabs/bin/puppet apply --modulepath=/etc/puppet/environments/aki/code/modules:/etc/puppet/environments/aki/code/r10k_modules --hiera_config=/etc/puppet/environments/aki/code/hiera.yaml --logdest=console --color=false --detailed-exitcodes /etc/puppet/environments/aki/code/manifests/ --test
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Notice: Compiled catalog for mac-v3-signing3.srv.releng.mdc1.mozilla.com in environment production in 0.04 seconds
Info: Applying configuration version '1592943273'
Notice: Applied catalog in 0.02 seconds
```

I usually have to run puppet through sudo on the testers. I ran the above through sudo/root and got the same result (no errors).

**Comment by escapewindow** [comment]
Abandoning dep. I'm going to open a clean PR and reference this one, with the caveats:
- we want to fix dep puppetizing at some point
- we'd like to revisit secrets storage
- this doesn't get us 100% of the way to no-ssh-upgrades, but it's good progress.

**Pull request closed without merging**
